//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinearGP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinearGP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;configuration&gt;
        ///&lt;parameters&gt;
        ///&lt;param name=&quot;NumRegisters&quot; value=&quot;6&quot; /&gt;
        ///&lt;param name=&quot;PopulationSize&quot; value=&quot;1000&quot; /&gt;
        ///&lt;param name=&quot;Epsilon&quot; value=&quot;0.000000001&quot; /&gt;
        ///&lt;param name=&quot;MaxGenerations&quot; value=&quot;1000&quot; /&gt;
        ///&lt;param name=&quot;Maximization&quot; value=&quot;false&quot; /&gt;
        ///&lt;param name=&quot;CrossoverRate&quot; value=&quot;0.1&quot; /&gt;
        ///&lt;param name=&quot;MacroMutationRate&quot; value=&quot;0.75&quot; /&gt;
        ///&lt;param name=&quot;MicroMutationRate&quot; value=&quot;0.25&quot; /&gt;
        ///&lt;/parameters&gt;
        ///
        ///&lt;log_parameters&gt;
        ///&lt;param name=&quot;PopLogInterval&quot; value=&quot;50&quot; /&gt;
        ///&lt;param nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LGPConfig {
            get {
                return ResourceManager.GetString("LGPConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;crossover strategy=&quot;linear&quot;&gt;
        ///
        ///&lt;strategy name=&quot;linear&quot; &gt;
        ///&lt;param name=&quot;max_program_length&quot; value=&quot;200&quot; /&gt;
        ///&lt;param name=&quot;min_program_length&quot; value=&quot;1&quot; /&gt;
        ///&lt;param name=&quot;max_segment_length&quot; value=&quot;5&quot; /&gt;
        ///&lt;param name=&quot;max_distance_of_crossover_points&quot; value=&quot;5&quot; /&gt;
        ///&lt;param name=&quot;max_difference_in_segment_length&quot; value=&quot;2&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;strategy name=&quot;one_point&quot; &gt;
        ///&lt;param name=&quot;max_program_length&quot; value=&quot;200&quot; /&gt;
        ///&lt;param name=&quot;min_program_length&quot; value=&quot;1&quot; /&gt;
        ///&lt;param name=&quot;max_distan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LGPCrossoverInstructionFactory {
            get {
                return ResourceManager.GetString("LGPCrossoverInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;pop_mutate strategy=&quot;macro_mutation&quot; &gt;
        ///
        ///&lt;strategy name=&quot;macro_mutation&quot;&gt;
        ///&lt;param name=&quot;insertion_mutation_probability&quot; value=&quot;0.5&quot; /&gt;
        ///&lt;param name=&quot;deletion_mutation_probability&quot; value=&quot;0.5&quot; /&gt; 
        ///&lt;param name=&quot;min_program_length&quot; value=&quot;1&quot; /&gt;
        ///&lt;param name=&quot;max_program_length&quot; value=&quot;200&quot; /&gt;
        ///&lt;param name=&quot;effective_mutation&quot; value=&quot;false&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/pop_mutate&gt;.
        /// </summary>
        internal static string LGPMutationInstructionFactory {
            get {
                return ResourceManager.GetString("LGPMutationInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;pop_init strategy=&quot;variable_length&quot;&gt;
        ///
        ///&lt;strategy name=&quot;variable_length&quot;&gt;
        ///&lt;param name=&quot;InitialMinProgLength&quot; value=&quot;5&quot; /&gt;
        ///&lt;param name=&quot;InitialMaxProgLength&quot; value=&quot;15&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;strategy name=&quot;constant_length&quot;&gt;
        ///&lt;param name=&quot;constant_length&quot; value=&quot;10&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/pop_init&gt;.
        /// </summary>
        internal static string LGPPopInitInstructionFactory {
            get {
                return ResourceManager.GetString("LGPPopInitInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;reg_init strategy=&quot;complete_initialization_of_register_with_input&quot;&gt;
        ///
        ///&lt;strategy name=&quot;complete_initialization_of_register_with_input&quot; &gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;strategy name=&quot;initialize_register_with_input&quot;&gt;
        ///&lt;param name=&quot;input_copy_count&quot; value=&quot;1&quot; /&gt;
        ///&lt;param name=&quot;default_register_value&quot; value=&quot;1&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;strategy name=&quot;copy_input_into_constant_set&quot;&gt;
        ///&lt;param name=&quot;default_register_value&quot; value=&quot;1&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/reg_init&gt;.
        /// </summary>
        internal static string LGPRegInitInstructionFactory {
            get {
                return ResourceManager.GetString("LGPRegInitInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;selection_config strategy=&quot;tournament&quot;&gt;
        ///
        ///&lt;strategy name=&quot;tournament&quot;&gt;
        ///&lt;param name=&quot;tournament_size&quot; value=&quot;2&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/selection_config&gt;.
        /// </summary>
        internal static string LGPReproductionSelectionInstructionFactory {
            get {
                return ResourceManager.GetString("LGPReproductionSelectionInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;survival_instruction strategy=&quot;probablistic&quot; &gt;
        ///
        ///&lt;strategy name=&quot;probablistic&quot; &gt;
        ///&lt;param name=&quot;reproduction_probability&quot; value=&quot;1&quot; /&gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;strategy name=&quot;compete&quot; &gt;
        ///&lt;/strategy&gt;
        ///
        ///&lt;/survival_instruction&gt;.
        /// </summary>
        internal static string LGPSurvivalInstructionFactory {
            get {
                return ResourceManager.GetString("LGPSurvivalInstructionFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;protected_definition&gt;
        ///
        ///&lt;C_undef use=&quot;low&quot;&gt;
        ///&lt;param name=&quot;low&quot; value=&quot;1&quot; /&gt;
        ///&lt;param name=&quot;high&quot; value=&quot;1000000&quot; /&gt;
        ///&lt;/C_undef&gt;
        ///
        ///&lt;LGP_REG_POSITIVE_INF value=&quot;10000000&quot; /&gt;
        ///&lt;LGP_REG_NEGATIVE_INF value=&quot;-10000000&quot; /&gt;
        ///
        ///&lt;/protected_definition&gt;.
        /// </summary>
        internal static string LGPUndefined {
            get {
                return ResourceManager.GetString("LGPUndefined", resourceCulture);
            }
        }
    }
}
